language: go

go:
  - "1.13.x"

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

stages:
  - unit-test

before_script:
  - make deps

jobs:
  include:
    - stage: unit-test
      name: "Run unit tests"
      script:
        - make test
